apiVersion: v1  
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
data:
  CART_PORT: "8080"
  CART_HOST: "cart"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
  AMQP_USER: "roboshop"
  AMQP_PASS: "roboshop123"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    component: payment
    tier: backend
spec:
  replicas: 1
  selector: #these are to select pod
    matchLabels:
      project: roboshop
      component: payment
      tier: backend
  template: #this info belongs to container/pod definition
    metadata:
      labels:
        project: roboshop
        component: payment
        tier: backend  
    spec:
      containers:
      - name: payment
        image: pravakula/payment:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: payment
        resources:  # java is resource intensive app, hence increase resource req and lim
          requests:
            cpu: "200m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 20
          initialDelaySeconds: 30
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 30
          initialDelaySeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: payment
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080  
---
#Horizontal Pod Autoscalar HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    component: payment
    tier: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # 70 is the real value